# Generated by Django 4.2.2 on 2023-06-13 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.TextField(default='0.0.0.0', max_length='12')),
                ('user_name', models.TextField()),
                ('user_cel', models.TextField(default='00000', max_length='10')),
                ('rating_value', models.CharField(default=0, max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant')),
            ],
        ),
    ]
